const baseLeads=[
{name:'Sarah Martinez',type:'Frameless shower enclosure',city:'Chula Vista',source:'Website',stage:'Qualified',timeline:'Within 30 days',slot:'Tuesday · 3–5 PM',value:2450,summary:'New residential enclosure. Tile complete. Clear glass. Brushed gold hardware. Photos requested.',contact:'Text preferred'},
{name:'David Nguyen',type:'Broken window',city:'Eastlake',source:'Google',stage:'New',timeline:'ASAP',slot:'—',value:0,summary:'Residential cracked pane. Property secured. Photo received.',contact:'Call preferred'},
{name:'Marisol Vega',type:'Glass railing',city:'Bonita',source:'Referral',stage:'Measured',timeline:'6–8 weeks',slot:'Measured Friday',value:6800,summary:'Exterior balcony railing. Approx. 24 linear ft. Modern clear-glass preference.',contact:'Text preferred'},
{name:'Harbor Point Market',type:'Commercial storefront',city:'San Diego',source:'Website',stage:'Follow-Up',timeline:'This month',slot:'Site walk requested',value:9200,summary:'Storefront door and glazing update. Property manager contact. Plans available.',contact:'Email preferred'},
{name:'Coastal Legal Group',type:'Office glass partition',city:'Chula Vista',source:'Referral',stage:'Estimate Sent',timeline:'Q4',slot:'Measured',value:11800,summary:'Interior conference-room partitions. Commercial tenant improvement.',contact:'Email preferred'},
{name:'Andrea Ruiz',type:'Custom mirror',city:'Otay Ranch',source:'Social',stage:'Measurement Booked',timeline:'2–4 weeks',slot:'Thursday · 9–11 AM',value:1400,summary:'Large wall mirror for home gym. Access notes captured.',contact:'Text preferred'}
];
let state={recovered:18600,measurementBooked:false,sarahStage:'Qualified',sarahWon:false,recoveryStep:0,recoveryChoice:'',lang:'en',scenario:'shower',photoCount:0};
let demoPhotos=[];
function load(){try{const s=JSON.parse(localStorage.getItem('cdoCicDemo'));if(s) state={...state,...s}}catch(e){};state.photoCount=0;demoPhotos=[];renderAll()}
function save(){try{localStorage.setItem('cdoCicDemo',JSON.stringify(state))}catch(e){};renderAll()}
function go(id){const target=document.getElementById(id);if(!target){id='home'}document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('[data-nav],[data-mob]').forEach(b=>b.classList.toggle('active',(b.dataset.nav||b.dataset.mob)===id));try{history.replaceState(null,'','#'+id)}catch(e){};window.scrollTo(0,0);if(id==='ava') initChat(false);}
function money(n){return '$'+n.toLocaleString('en-US')}
function resetDemo(){demoPhotos.forEach(p=>{try{URL.revokeObjectURL(p.url)}catch(e){}});demoPhotos=[];window.selectedLead=0;state={recovered:18600,measurementBooked:false,sarahStage:'Qualified',sarahWon:false,recoveryStep:0,recoveryChoice:'',lang:'en',scenario:'shower',photoCount:0};try{localStorage.removeItem('cdoCicDemo')}catch(e){};const input=document.getElementById('photoInput');if(input)input.value='';const toast=document.getElementById('demoToast');if(toast)toast.remove();renderPhotoTray();renderAll();initChat(true);go('home')}
function renderAll(){document.getElementById('homeRecovered').textContent=money(state.recovered);document.getElementById('dashRecovered').textContent=money(state.recovered);document.getElementById('homeBooked').textContent=state.measurementBooked?'7':'6';document.getElementById('dashBooked').textContent=state.measurementBooked?'7':'6';document.getElementById('openValue').textContent=state.sarahWon?'$28,950':'$31,400';renderPipeline();renderRecovery();renderActivity();document.getElementById('langBtn').textContent=state.lang==='en'?'Español':'English'}
function renderActivity(){const items=[['Ava',state.photoCount?`Qualified shower inquiry · ${state.photoCount} photo${state.photoCount===1?'':'s'} attached`:'Qualified a shower inquiry'],['Sophia',state.measurementBooked?'Confirmed Sarah’s measurement':'Prepared a measurement request'],['Mia',state.sarahWon?'Recovered Sarah’s $2,450 estimate':'Monitoring 3 quiet estimates'],['Olivia','Queued a post-install check-in']];document.getElementById('activity').innerHTML=items.map(x=>`<div class="att"><span><b>${x[0]}</b><br><span class="tiny">${x[1]}</span></span><span class="pill">Today</span></div>`).join('')}
const stages=['New','Qualified','Measurement Booked','Measured','Estimate Sent','Follow-Up','Won','Lost / Nurture'];
function renderPipeline(){const sb=document.getElementById('stagebar');if(!sb)return;sb.innerHTML=stages.map(s=>`<div class="stage ${state.sarahStage===s?'sel':''}">${s}</div>`).join('');const leads=baseLeads.map((l,i)=>i?l:{...l,stage:state.sarahStage});document.getElementById('leadlist').innerHTML='<h3>Opportunities</h3>'+leads.map((l,i)=>`<div class="lead ${i===(window.selectedLead||0)?'sel':''}" onclick="selectLead(${i})"><div class="leadtop"><b>${l.name}</b><span class="pill">${l.stage}</span></div><div class="tiny" style="margin-top:5px">${l.type} · ${l.city}</div></div>`).join('');selectLead(window.selectedLead||0)}
window.selectedLead=0;
function photoAttachmentHtml(){if(!state.photoCount||!demoPhotos.length)return '<div class="datum" style="margin-top:10px"><span>Project photos</span><span class="muted" style="text-transform:none;letter-spacing:0;font-size:13px">No demo photos attached yet. Add them in Ava and they will appear here automatically.</span></div>';const photos=demoPhotos.map((p,idx)=>`<div class="photoTile">${p.preview?`<img src="${p.url}" alt="Project photo ${idx+1}">`:`<div class="photoFallback">▧</div>`}<span>${escapeHtml(p.name)}</span></div>`).join('');return `<div class="datum" style="margin-top:10px"><span>Project photos · ${state.photoCount} attached</span><div class="photoStrip">${photos}</div></div>`}
function selectLead(i){window.selectedLead=i;document.querySelectorAll('#leadlist .lead').forEach((el,idx)=>el.classList.toggle('sel',idx===i));const l=i===0?{...baseLeads[0],stage:state.sarahStage}:baseLeads[i];const d=document.getElementById('detail');if(!d)return;const photoSummary=i===0&&state.photoCount?` ${state.photoCount} project photo${state.photoCount===1?'':'s'} attached from Ava.`:'';d.innerHTML=`<div class="leadtop"><div><div class="tiny">${l.source.toUpperCase()} LEAD</div><h3 style="font-size:28px;margin:6px 0">${l.name}</h3><div class="muted">${l.type}</div></div><span class="pill">${l.stage}</span></div><div class="detailgrid"><div class="datum"><span>Location</span>${l.city}</div><div class="datum"><span>Contact</span>${l.contact}</div><div class="datum"><span>Timeline</span>${l.timeline}</div><div class="datum"><span>Measurement</span>${l.slot}</div></div><div class="datum"><span>Conversation summary</span>${l.summary}${photoSummary}</div>${i===0?photoAttachmentHtml():''}${i===0?`<div class="actions" style="margin-top:16px"><button class="btn primary" onclick="confirmMeasurement()">Confirm Measurement</button><button class="btn secondary" onclick="sendEstimate()">Send $2,450 Estimate</button><button class="btn secondary" onclick="demoAction('Call task created for the CDO team.')">Call Customer</button><button class="btn secondary" onclick="demoAction('Sarah assigned to a CDO team member.')">Assign</button></div><div class="ctas"><button class="btn secondary" onclick="go('recovery')">Next: Recover the estimate →</button></div>`:''}`}
function demoAction(message){const old=document.getElementById('demoToast');if(old)old.remove();const n=document.createElement('div');n.id='demoToast';n.textContent=message;n.style.cssText='position:fixed;right:18px;top:84px;z-index:80;background:#10202b;border:1px solid rgba(85,215,242,.28);color:#e8faff;padding:12px 15px;border-radius:14px;box-shadow:0 18px 50px rgba(0,0,0,.35);font-size:13px;max-width:320px';document.body.appendChild(n);setTimeout(()=>n.remove(),2400)}
function confirmMeasurement(){state.measurementBooked=true;state.sarahStage='Measurement Booked';save()}
function sendEstimate(){state.measurementBooked=true;state.sarahStage='Estimate Sent';save();go('recovery')}
function renderRecovery(){const tl=document.getElementById('recoveryTimeline'),ac=document.getElementById('recoveryActions'),st=document.getElementById('recoveryStatus');if(!tl)return;const isTiming=state.recoveryChoice==='timing';let events=[['CDO estimate sent','$2,450 · Sarah Martinez · Frameless shower enclosure']];if(state.recoveryStep>=1)events.push(['Mia follow-up','“Hi Sarah — I wanted to make sure you received the CDO Glass estimate for your shower enclosure. If you have questions about the project or next steps, I can help get them to the team.”']);if(state.recoveryStep>=2)events.push(['Customer reply',isTiming?'“We’re still deciding on timing.”':'“We’re comparing another company that’s a little cheaper.”']);if(state.recoveryStep>=3)events.push(['Mia response',isTiming?'“No problem. I can keep the project open and make sure the CDO team follows up closer to your preferred timing. Would next month be better?”':'“Completely understandable. If you have a written quote from another licensed contractor, I can send it to the CDO team for review. They’ll confirm what options are available.”']);if(state.recoveryStep>=4)events.push(['Human review',isTiming?'CDO confirms the best follow-up window and keeps the opportunity active.':'CDO reviews the competing written quote and decides the next step.']);if(state.sarahWon)events.push(['Customer accepted','Sarah moved to Won. Recovered revenue increased by $2,450.']);tl.innerHTML=events.map(e=>`<div class="event"><b>${e[0]}</b><div class="muted">${e[1]}</div></div>`).join('');st.textContent=state.sarahWon?'Won':(state.recoveryStep>=1?'Follow-Up':'Estimate Sent');if(state.sarahWon){ac.innerHTML=`<div class="success"><b>Recovered: +$2,450</b><div class="tiny">Owner dashboard is now ${money(state.recovered)}.</div><button class="btn primary" style="margin-top:12px" onclick="go('dashboard')">Open Owner Dashboard →</button></div>`;return}if(state.recoveryStep===0)ac.innerHTML=`<button class="btn primary" onclick="recStep(1)">Start Recovery</button>`;else if(state.recoveryStep===1)ac.innerHTML=`<div class="choice"><button onclick="chooseRecovery('price')">Customer: “We’re comparing another company that’s a little cheaper.”</button><button onclick="chooseRecovery('timing')">Customer: “We’re still deciding on timing.”</button></div>`;else if(state.recoveryStep===2)ac.innerHTML=`<button class="btn primary" onclick="recStep(3)">Let Mia respond</button>`;else if(state.recoveryStep===3)ac.innerHTML=`<button class="btn primary" onclick="recStep(4)">${isTiming?'Confirm follow-up plan':'Escalate to CDO for review'}</button>`;else ac.innerHTML=`<button class="btn primary" onclick="acceptSarah()">Customer Accepted</button>`}
function recStep(n){state.recoveryStep=n;save()}
function chooseRecovery(choice){state.recoveryChoice=choice;state.recoveryStep=2;save()}
function acceptSarah(){if(!state.sarahWon){state.sarahWon=true;state.sarahStage='Won';state.recovered+=2450}save()}
